version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9

conda:
  environment: doc/requirements.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: doc/conf.py
  # This is deliberately laxer than the setting in CI
  fail_on_warning: false
