#!/usr/bin/env bash
# shellcheck disable=SC2016

set -o errexit

cd "$(dirname "$0")"
echo '# File generated by `requirements-export.sh`' > requirements.yml
pixi workspace export conda-environment -e docs >> requirements.yml
sed -i '${/^$/d;}' requirements.yml  # remove last empty line
