name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.55.0
          cache: true
          environments: docs

      - name: Regenerate readthedocs environment
        run: pixi run doc-requirements

      - name: Check that readthedocs environment is up to date in git
        run: git diff --exit-code doc/requirements.yml

      - name: Build docs
        run: pixi run -e docs docs

      - uses: actions/upload-artifact@v4
        with:
          name: pyscenarios-docs
          path: build/html
